apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
spec:
  containers:
    - name: hello-world-container
      image: non_existing_image
      command:
        - "sh"
        - "-c"
        - "while true; do echo 'Hello World'; sleep 5; done"
