apiVersion: v1
kind: Pod
metadata:
  name: check-userid-pod
  labels:
    app: check-userid
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: [ "sh", "-c", "sleep 3600" ]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
      securityContext:
        runAsUser: 0
