apiVersion: v1
kind: Pod
metadata:
  name: user-test-pod
spec:
  containers:
    - name: user-test-container
      image: ubuntu:20.04
      command: ["sleep", "3600"]
      securityContext:
        runAsUser: 1000
